### ISSUE TITLE
关于IVUSchallenge2011的数据

### ISSUE THREAD

**Issue by jyxiong** [Kulbear/ivus-segmentation-icsm2018#1]
你好：

在读到您的文章《IVUS-Net: An Intravascular Ultrasound Segmentation Network》时，发现您提供了相关的代码，想重复一下您的实验。但是[原数据网址](http://www.cvc.uab.es/IVUSchallenge2011/about.html)已经不能提供下载了，请问您有什么解决的办法吗

谢谢

**Comment by Kulbear** [comment]
@jyxiong 可以试着给原作者发一下邮件 这个dataset应该是有credential的。

**Comment by jyxiong** [comment]
@Mehdi-Faraji  好的好的，谢谢

**Comment by onebad-bit** [comment]
@jyxiong 您好，我也在实现这个实验，请问关于IVUSchallenge2011的数据您找到了嘛，方便的话能和我联系嘛？

**Comment by jyxiong** [comment]
> @jyxiong 您好，我也在实现这个实验，请问关于IVUSchallenge2011的数据您找到了嘛，方便的话能和我联系嘛？

发邮件给原作者就行啦，很快就有回复给个链接。

**Comment by onebad-bit** [comment]
@jyxiong 好的，多谢，我给作者发邮件咨询下。

**Comment by onebad-bit** [comment]
@jyxiong 您好，我想再请问一下，您是给《IVUS-Net: An Intravascular Ultrasound Segmentation Network》这篇文章的第一作者jyang7@ualberta.ca发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了

**Comment by jyxiong** [comment]
> @jyxiong 您好，我想再请问一下，您是给《IVUS-Net: An Intravascular Ultrasound Segmentation Network》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了

给数据库的作者，这篇文章《IVUS-Net: An Intravascular Ultrasound Segmentation Network》里引用的文献[3]的作者。

**Comment by Kulbear** [comment]
@onebad-bit @jyxiong 
Hi我刚看到了你的邮件。

这个数据集我们不能redistribute，还是麻烦你给数据集paper的作者发一下邮件。

**Comment by onebad-bit** [comment]
好的

**Comment by 6yujie** [comment]
> > @jyxiong 您好，我也在实现这个实验，请问关于IVUSchallenge2011的数据您找到了嘛，方便的话能和我联系嘛？
> 
> 发邮件给原作者就行啦，很快就有回复给个链接。

你好，请问给原作者发送邮件后大概多久会回复呀？我发邮件有两天了，还是没有消息。

**Comment by yangyulong929** [comment]
> > @jyxiong您好，我也在实现这个实验，请问关于IVUSchallenge2011的数据您找到了嘛，方便的话能和我联系嘛？
> 
> 发邮件给原作者就行啦，很快就有回复给个链接。

你能提供一下链接吗

**Comment by keepoptimistic** [comment]
您好，可以发我一份RF数据集吗？

**Comment by yangyulong929** [comment]
数据集作者说了，这个数据集不公开了，拿到了也没用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "keepoptimistic"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 中午11:43
收件人: "Kulbear/ivus-segmentation-icsm2018"<ivus-segmentation-icsm2018@noreply.github.com&gt;; 
抄送: "三生有幸"<1043938883@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Kulbear/ivus-segmentation-icsm2018] 关于IVUSchallenge2011的数据 (#1)





 
您好，可以发我一份RF数据集吗？

**Comment by yangyulong929** [comment]
> 您好，可以发我一份RF数据集吗？

1043938883,加个好友沟通一下

**Comment by keepoptimistic** [comment]
> > 您好，可以发我一份RF数据集吗？
> 
> 1043938883,加个好友沟通一下

加了。

**Comment by HsienJuWu** [comment]
您好，我也有加你qq，可以跟你要一份RF數據嗎

**Comment by KuoYa233** [comment]
> > @jyxiong 您好，我想再请问一下，您是给《IVUS-Net: An Intravascular Ultrasound Segmentation Network》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了
> 
> 给数据库的作者，这篇文章《IVUS-Net: An Intravascular Ultrasound Segmentation Network》里引用的文献[3]的作者。

你好，我给文献[3]的通讯Prof. Simone Balocco申请IVUS数据集，他不给。方便的话，您可以给我发一份吗？

**Comment by Swecamellia** [comment]
你好，我想请问一下找他要这个数据需要什么condition吗？我刚刚给他发邮件，他说不符合条件，不能分享qwq

**Comment by CyberKing0514** [comment]
> > @jyxiong 您好，我想再请问一下，您是给《IVUS-Net: An Intravascular Ultrasound Segmentation Network》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了
> 
> 给数据库的作者，这篇文章《IVUS-Net: An Intravascular Ultrasound Segmentation Network》里引用的文献[3]的作者。

你好，我最近也给Prof. Simone Balocco申请IVUS数据集了，但是他不给。请问你当时是怎么跟他沟通的呢？或者方便的话能发我一份吗？

**Comment by HaohuiHU** [comment]
> > > [@jyxiong](https://github.com/jyxiong)您好，我想再问一下，您是给《IVUS-Net：血管内超声分割网络》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了
> > 
> > 
> > 给数据库的作者，这篇文章《IVUS-Net：血管内超声分割网络》里引用的文献[3]的作者。
> 
> 你好，我最近也给Prof. Simone Balocco申请IVUS数据集了，但是他不给。请问你当时是怎么跟他沟通的呢？或者方便的话能发给我一份吗？

**Comment by HaohuiHU** [comment]
> > > [@jyxiong](https://github.com/jyxiong)您好，我想再问一下，您是给《IVUS-Net：血管内超声分割网络》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了
> > 
> > 
> > 给数据库的作者，这篇文章《IVUS-Net：血管内超声分割网络》里引用的文献[3]的作者。
> 
> 你好，我最近也给Prof. Simone Balocco申请IVUS数据集了，但是他不给。请问你当时是怎么跟他沟通的呢？或者方便的话能发给我一份吗？
Could you please get the data?

**Comment by Swiffany** [comment]
> > [@jyxiong](https://github.com/jyxiong) 您好，我也在实现这个实验，请问关于IVUSchallenge2011的数据您找到了嘛，方便的话能和我联系嘛？
> 
> 发邮件给原作者就行啦，很快就有回复给个链接。
@jyxiong 您好，请问方便把数据集分享一份吗？非常感谢！邮箱：swiffanylee@gmail.com

**Comment by 18351501117liu-design** [comment]
> > > [@jyxiong](https://github.com/jyxiong) 您好，我想再请问一下，您是给《IVUS-Net: An Intravascular Ultrasound Segmentation Network》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了
> > 
> > 
> > 给数据库的作者，这篇文章《IVUS-Net: An Intravascular Ultrasound Segmentation Network》里引用的文献[3]的作者。
> 
> 你好，我最近也给Prof. Simone Balocco申请IVUS数据集了，但是他不给。请问你当时是怎么跟他沟通的呢？或者方便的话能发我一份吗？

>您好,我也无法联系到Prof. Simone Balocco,请问您找到数据集了吗,是否可以分享?邮箱:liujie_louis@163.com

**Comment by malvin-chen** [comment]
> > [@jyxiong](https://github.com/jyxiong) 您好，我想再请问一下，您是给《IVUS-Net: An Intravascular Ultrasound Segmentation Network》这篇文章的第一作者[jyang7@ualberta.ca](mailto:jyang7@ualberta.ca)发的邮件嘛，我发了两天现在没有回复我，我担心是不是发错了
> 
> 给数据库的作者，这篇文章《IVUS-Net: An Intravascular Ultrasound Segmentation Network》里引用的文献[3]的作者。

@jyxiong 你好，请问你拿到数据集了吗？我找了Prof. Simone Balocco，他没给。能否分享一下，万分感激！！邮箱：malvin.chen@outlook.com
